###########################################
# BASE IMAGE
###########################################

FROM ubuntu AS build

RUN apt-get update && apt-get install -y golang-go

ENV GO111MODULE=off

WORKDIR /src
COPY . .

#  Build the binary into a proper directory
RUN mkdir -p /out
RUN CGO_ENABLED=0 go build -o /out/simplecalculator .

############################################
# FINAL STAGE (MINIMAL)
############################################

FROM scratch

# Create a directory /app and copy the binary into it
COPY --from=build /out/simplecalculator /app/simplecalculator

# Set entrypoint to the binary
ENTRYPOINT ["/app/simplecalculator"]

